//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WzorceProjektowe
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PatternsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PatternsEntities object using the connection string found in the 'PatternsEntities' section of the application configuration file.
        /// </summary>
        public PatternsEntities() : base("name=PatternsEntities", "PatternsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PatternsEntities object.
        /// </summary>
        public PatternsEntities(string connectionString) : base(connectionString, "PatternsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PatternsEntities object.
        /// </summary>
        public PatternsEntities(EntityConnection connection) : base(connection, "PatternsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Odpowiedzi> Odpowiedzi
        {
            get
            {
                if ((_Odpowiedzi == null))
                {
                    _Odpowiedzi = base.CreateObjectSet<Odpowiedzi>("Odpowiedzi");
                }
                return _Odpowiedzi;
            }
        }
        private ObjectSet<Odpowiedzi> _Odpowiedzi;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pytania> Pytania
        {
            get
            {
                if ((_Pytania == null))
                {
                    _Pytania = base.CreateObjectSet<Pytania>("Pytania");
                }
                return _Pytania;
            }
        }
        private ObjectSet<Pytania> _Pytania;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pytania_Odpowiedzi> Pytania_Odpowiedzi
        {
            get
            {
                if ((_Pytania_Odpowiedzi == null))
                {
                    _Pytania_Odpowiedzi = base.CreateObjectSet<Pytania_Odpowiedzi>("Pytania_Odpowiedzi");
                }
                return _Pytania_Odpowiedzi;
            }
        }
        private ObjectSet<Pytania_Odpowiedzi> _Pytania_Odpowiedzi;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rozwiazane_quizy> Rozwiazane_quizy
        {
            get
            {
                if ((_Rozwiazane_quizy == null))
                {
                    _Rozwiazane_quizy = base.CreateObjectSet<Rozwiazane_quizy>("Rozwiazane_quizy");
                }
                return _Rozwiazane_quizy;
            }
        }
        private ObjectSet<Rozwiazane_quizy> _Rozwiazane_quizy;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Uzytkownicy> Uzytkownicy
        {
            get
            {
                if ((_Uzytkownicy == null))
                {
                    _Uzytkownicy = base.CreateObjectSet<Uzytkownicy>("Uzytkownicy");
                }
                return _Uzytkownicy;
            }
        }
        private ObjectSet<Uzytkownicy> _Uzytkownicy;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Zadane_pytania> Zadane_pytania
        {
            get
            {
                if ((_Zadane_pytania == null))
                {
                    _Zadane_pytania = base.CreateObjectSet<Zadane_pytania>("Zadane_pytania");
                }
                return _Zadane_pytania;
            }
        }
        private ObjectSet<Zadane_pytania> _Zadane_pytania;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Odpowiedzi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOdpowiedzi(Odpowiedzi odpowiedzi)
        {
            base.AddObject("Odpowiedzi", odpowiedzi);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pytania EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPytania(Pytania pytania)
        {
            base.AddObject("Pytania", pytania);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pytania_Odpowiedzi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPytania_Odpowiedzi(Pytania_Odpowiedzi pytania_Odpowiedzi)
        {
            base.AddObject("Pytania_Odpowiedzi", pytania_Odpowiedzi);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rozwiazane_quizy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRozwiazane_quizy(Rozwiazane_quizy rozwiazane_quizy)
        {
            base.AddObject("Rozwiazane_quizy", rozwiazane_quizy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Uzytkownicy EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUzytkownicy(Uzytkownicy uzytkownicy)
        {
            base.AddObject("Uzytkownicy", uzytkownicy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Zadane_pytania EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZadane_pytania(Zadane_pytania zadane_pytania)
        {
            base.AddObject("Zadane_pytania", zadane_pytania);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PatternsDatabaseModel", Name="Odpowiedzi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Odpowiedzi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Odpowiedzi object.
        /// </summary>
        /// <param name="iD_odpowiedzi">Initial value of the ID_odpowiedzi property.</param>
        /// <param name="tresc_odpowiedzi">Initial value of the Tresc_odpowiedzi property.</param>
        public static Odpowiedzi CreateOdpowiedzi(global::System.Int32 iD_odpowiedzi, global::System.String tresc_odpowiedzi)
        {
            Odpowiedzi odpowiedzi = new Odpowiedzi();
            odpowiedzi.ID_odpowiedzi = iD_odpowiedzi;
            odpowiedzi.Tresc_odpowiedzi = tresc_odpowiedzi;
            return odpowiedzi;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_odpowiedzi
        {
            get
            {
                return _ID_odpowiedzi;
            }
            set
            {
                if (_ID_odpowiedzi != value)
                {
                    OnID_odpowiedziChanging(value);
                    ReportPropertyChanging("ID_odpowiedzi");
                    _ID_odpowiedzi = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_odpowiedzi");
                    OnID_odpowiedziChanged();
                }
            }
        }
        private global::System.Int32 _ID_odpowiedzi;
        partial void OnID_odpowiedziChanging(global::System.Int32 value);
        partial void OnID_odpowiedziChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tresc_odpowiedzi
        {
            get
            {
                return _Tresc_odpowiedzi;
            }
            set
            {
                OnTresc_odpowiedziChanging(value);
                ReportPropertyChanging("Tresc_odpowiedzi");
                _Tresc_odpowiedzi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tresc_odpowiedzi");
                OnTresc_odpowiedziChanged();
            }
        }
        private global::System.String _Tresc_odpowiedzi;
        partial void OnTresc_odpowiedziChanging(global::System.String value);
        partial void OnTresc_odpowiedziChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PatternsDatabaseModel", Name="Pytania")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pytania : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pytania object.
        /// </summary>
        /// <param name="iD_pytania">Initial value of the ID_pytania property.</param>
        /// <param name="poziom_trudnosci">Initial value of the Poziom_trudnosci property.</param>
        public static Pytania CreatePytania(global::System.Int32 iD_pytania, global::System.String poziom_trudnosci)
        {
            Pytania pytania = new Pytania();
            pytania.ID_pytania = iD_pytania;
            pytania.Poziom_trudnosci = poziom_trudnosci;
            return pytania;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_pytania
        {
            get
            {
                return _ID_pytania;
            }
            set
            {
                if (_ID_pytania != value)
                {
                    OnID_pytaniaChanging(value);
                    ReportPropertyChanging("ID_pytania");
                    _ID_pytania = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_pytania");
                    OnID_pytaniaChanged();
                }
            }
        }
        private global::System.Int32 _ID_pytania;
        partial void OnID_pytaniaChanging(global::System.Int32 value);
        partial void OnID_pytaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Poziom_trudnosci
        {
            get
            {
                return _Poziom_trudnosci;
            }
            set
            {
                OnPoziom_trudnosciChanging(value);
                ReportPropertyChanging("Poziom_trudnosci");
                _Poziom_trudnosci = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Poziom_trudnosci");
                OnPoziom_trudnosciChanged();
            }
        }
        private global::System.String _Poziom_trudnosci;
        partial void OnPoziom_trudnosciChanging(global::System.String value);
        partial void OnPoziom_trudnosciChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tresc_pytania
        {
            get
            {
                return _Tresc_pytania;
            }
            set
            {
                OnTresc_pytaniaChanging(value);
                ReportPropertyChanging("Tresc_pytania");
                _Tresc_pytania = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tresc_pytania");
                OnTresc_pytaniaChanged();
            }
        }
        private global::System.String _Tresc_pytania;
        partial void OnTresc_pytaniaChanging(global::System.String value);
        partial void OnTresc_pytaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Obrazek
        {
            get
            {
                return StructuralObject.GetValidValue(_Obrazek);
            }
            set
            {
                OnObrazekChanging(value);
                ReportPropertyChanging("Obrazek");
                _Obrazek = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Obrazek");
                OnObrazekChanged();
            }
        }
        private global::System.Byte[] _Obrazek;
        partial void OnObrazekChanging(global::System.Byte[] value);
        partial void OnObrazekChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PatternsDatabaseModel", Name="Pytania_Odpowiedzi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pytania_Odpowiedzi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pytania_Odpowiedzi object.
        /// </summary>
        /// <param name="iD_odpowiedzi">Initial value of the ID_odpowiedzi property.</param>
        /// <param name="iD_pytania">Initial value of the ID_pytania property.</param>
        /// <param name="czy_odp_ok">Initial value of the Czy_odp_ok property.</param>
        public static Pytania_Odpowiedzi CreatePytania_Odpowiedzi(global::System.Int32 iD_odpowiedzi, global::System.Int32 iD_pytania, global::System.Boolean czy_odp_ok)
        {
            Pytania_Odpowiedzi pytania_Odpowiedzi = new Pytania_Odpowiedzi();
            pytania_Odpowiedzi.ID_odpowiedzi = iD_odpowiedzi;
            pytania_Odpowiedzi.ID_pytania = iD_pytania;
            pytania_Odpowiedzi.Czy_odp_ok = czy_odp_ok;
            return pytania_Odpowiedzi;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_odpowiedzi
        {
            get
            {
                return _ID_odpowiedzi;
            }
            set
            {
                if (_ID_odpowiedzi != value)
                {
                    OnID_odpowiedziChanging(value);
                    ReportPropertyChanging("ID_odpowiedzi");
                    _ID_odpowiedzi = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_odpowiedzi");
                    OnID_odpowiedziChanged();
                }
            }
        }
        private global::System.Int32 _ID_odpowiedzi;
        partial void OnID_odpowiedziChanging(global::System.Int32 value);
        partial void OnID_odpowiedziChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_pytania
        {
            get
            {
                return _ID_pytania;
            }
            set
            {
                if (_ID_pytania != value)
                {
                    OnID_pytaniaChanging(value);
                    ReportPropertyChanging("ID_pytania");
                    _ID_pytania = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_pytania");
                    OnID_pytaniaChanged();
                }
            }
        }
        private global::System.Int32 _ID_pytania;
        partial void OnID_pytaniaChanging(global::System.Int32 value);
        partial void OnID_pytaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Czy_odp_ok
        {
            get
            {
                return _Czy_odp_ok;
            }
            set
            {
                if (_Czy_odp_ok != value)
                {
                    OnCzy_odp_okChanging(value);
                    ReportPropertyChanging("Czy_odp_ok");
                    _Czy_odp_ok = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Czy_odp_ok");
                    OnCzy_odp_okChanged();
                }
            }
        }
        private global::System.Boolean _Czy_odp_ok;
        partial void OnCzy_odp_okChanging(global::System.Boolean value);
        partial void OnCzy_odp_okChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PatternsDatabaseModel", Name="Rozwiazane_quizy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rozwiazane_quizy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rozwiazane_quizy object.
        /// </summary>
        /// <param name="iD_rozwiazanegoquizu">Initial value of the ID_rozwiazanegoquizu property.</param>
        /// <param name="statusq">Initial value of the Statusq property.</param>
        /// <param name="liczba_pytan">Initial value of the Liczba_pytan property.</param>
        /// <param name="liczba_poprodp">Initial value of the Liczba_poprodp property.</param>
        /// <param name="liczba_niepoprodp">Initial value of the Liczba_niepoprodp property.</param>
        /// <param name="wynik">Initial value of the Wynik property.</param>
        /// <param name="iD_user">Initial value of the ID_user property.</param>
        /// <param name="poziom_trudnosci">Initial value of the Poziom_trudnosci property.</param>
        public static Rozwiazane_quizy CreateRozwiazane_quizy(global::System.Int32 iD_rozwiazanegoquizu, global::System.Boolean statusq, global::System.Int32 liczba_pytan, global::System.Int32 liczba_poprodp, global::System.Int32 liczba_niepoprodp, global::System.Decimal wynik, global::System.Int32 iD_user, global::System.Int32 poziom_trudnosci)
        {
            Rozwiazane_quizy rozwiazane_quizy = new Rozwiazane_quizy();
            rozwiazane_quizy.ID_rozwiazanegoquizu = iD_rozwiazanegoquizu;
            rozwiazane_quizy.Statusq = statusq;
            rozwiazane_quizy.Liczba_pytan = liczba_pytan;
            rozwiazane_quizy.Liczba_poprodp = liczba_poprodp;
            rozwiazane_quizy.Liczba_niepoprodp = liczba_niepoprodp;
            rozwiazane_quizy.Wynik = wynik;
            rozwiazane_quizy.ID_user = iD_user;
            rozwiazane_quizy.Poziom_trudnosci = poziom_trudnosci;
            return rozwiazane_quizy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_rozwiazanegoquizu
        {
            get
            {
                return _ID_rozwiazanegoquizu;
            }
            set
            {
                if (_ID_rozwiazanegoquizu != value)
                {
                    OnID_rozwiazanegoquizuChanging(value);
                    ReportPropertyChanging("ID_rozwiazanegoquizu");
                    _ID_rozwiazanegoquizu = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_rozwiazanegoquizu");
                    OnID_rozwiazanegoquizuChanged();
                }
            }
        }
        private global::System.Int32 _ID_rozwiazanegoquizu;
        partial void OnID_rozwiazanegoquizuChanging(global::System.Int32 value);
        partial void OnID_rozwiazanegoquizuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Statusq
        {
            get
            {
                return _Statusq;
            }
            set
            {
                OnStatusqChanging(value);
                ReportPropertyChanging("Statusq");
                _Statusq = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Statusq");
                OnStatusqChanged();
            }
        }
        private global::System.Boolean _Statusq;
        partial void OnStatusqChanging(global::System.Boolean value);
        partial void OnStatusqChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Liczba_pytan
        {
            get
            {
                return _Liczba_pytan;
            }
            set
            {
                OnLiczba_pytanChanging(value);
                ReportPropertyChanging("Liczba_pytan");
                _Liczba_pytan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Liczba_pytan");
                OnLiczba_pytanChanged();
            }
        }
        private global::System.Int32 _Liczba_pytan;
        partial void OnLiczba_pytanChanging(global::System.Int32 value);
        partial void OnLiczba_pytanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Liczba_poprodp
        {
            get
            {
                return _Liczba_poprodp;
            }
            set
            {
                OnLiczba_poprodpChanging(value);
                ReportPropertyChanging("Liczba_poprodp");
                _Liczba_poprodp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Liczba_poprodp");
                OnLiczba_poprodpChanged();
            }
        }
        private global::System.Int32 _Liczba_poprodp;
        partial void OnLiczba_poprodpChanging(global::System.Int32 value);
        partial void OnLiczba_poprodpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Liczba_niepoprodp
        {
            get
            {
                return _Liczba_niepoprodp;
            }
            set
            {
                OnLiczba_niepoprodpChanging(value);
                ReportPropertyChanging("Liczba_niepoprodp");
                _Liczba_niepoprodp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Liczba_niepoprodp");
                OnLiczba_niepoprodpChanged();
            }
        }
        private global::System.Int32 _Liczba_niepoprodp;
        partial void OnLiczba_niepoprodpChanging(global::System.Int32 value);
        partial void OnLiczba_niepoprodpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Wynik
        {
            get
            {
                return _Wynik;
            }
            set
            {
                OnWynikChanging(value);
                ReportPropertyChanging("Wynik");
                _Wynik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Wynik");
                OnWynikChanged();
            }
        }
        private global::System.Decimal _Wynik;
        partial void OnWynikChanging(global::System.Decimal value);
        partial void OnWynikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_user
        {
            get
            {
                return _ID_user;
            }
            set
            {
                OnID_userChanging(value);
                ReportPropertyChanging("ID_user");
                _ID_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_user");
                OnID_userChanged();
            }
        }
        private global::System.Int32 _ID_user;
        partial void OnID_userChanging(global::System.Int32 value);
        partial void OnID_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Poziom_trudnosci
        {
            get
            {
                return _Poziom_trudnosci;
            }
            set
            {
                OnPoziom_trudnosciChanging(value);
                ReportPropertyChanging("Poziom_trudnosci");
                _Poziom_trudnosci = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Poziom_trudnosci");
                OnPoziom_trudnosciChanged();
            }
        }
        private global::System.Int32 _Poziom_trudnosci;
        partial void OnPoziom_trudnosciChanging(global::System.Int32 value);
        partial void OnPoziom_trudnosciChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PatternsDatabaseModel", Name="Uzytkownicy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Uzytkownicy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Uzytkownicy object.
        /// </summary>
        /// <param name="iD_user">Initial value of the ID_user property.</param>
        public static Uzytkownicy CreateUzytkownicy(global::System.Int32 iD_user)
        {
            Uzytkownicy uzytkownicy = new Uzytkownicy();
            uzytkownicy.ID_user = iD_user;
            return uzytkownicy;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_user
        {
            get
            {
                return _ID_user;
            }
            set
            {
                if (_ID_user != value)
                {
                    OnID_userChanging(value);
                    ReportPropertyChanging("ID_user");
                    _ID_user = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_user");
                    OnID_userChanged();
                }
            }
        }
        private global::System.Int32 _ID_user;
        partial void OnID_userChanging(global::System.Int32 value);
        partial void OnID_userChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PatternsDatabaseModel", Name="Zadane_pytania")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Zadane_pytania : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Zadane_pytania object.
        /// </summary>
        /// <param name="iD_zadanegopytania">Initial value of the ID_zadanegopytania property.</param>
        /// <param name="iD_rozwiazanegoquizu">Initial value of the ID_rozwiazanegoquizu property.</param>
        /// <param name="iD_pytania">Initial value of the ID_pytania property.</param>
        /// <param name="iD_udzielonejodp">Initial value of the ID_udzielonejodp property.</param>
        public static Zadane_pytania CreateZadane_pytania(global::System.Int32 iD_zadanegopytania, global::System.Int32 iD_rozwiazanegoquizu, global::System.Int32 iD_pytania, global::System.Int32 iD_udzielonejodp)
        {
            Zadane_pytania zadane_pytania = new Zadane_pytania();
            zadane_pytania.ID_zadanegopytania = iD_zadanegopytania;
            zadane_pytania.ID_rozwiazanegoquizu = iD_rozwiazanegoquizu;
            zadane_pytania.ID_pytania = iD_pytania;
            zadane_pytania.ID_udzielonejodp = iD_udzielonejodp;
            return zadane_pytania;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_zadanegopytania
        {
            get
            {
                return _ID_zadanegopytania;
            }
            set
            {
                if (_ID_zadanegopytania != value)
                {
                    OnID_zadanegopytaniaChanging(value);
                    ReportPropertyChanging("ID_zadanegopytania");
                    _ID_zadanegopytania = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_zadanegopytania");
                    OnID_zadanegopytaniaChanged();
                }
            }
        }
        private global::System.Int32 _ID_zadanegopytania;
        partial void OnID_zadanegopytaniaChanging(global::System.Int32 value);
        partial void OnID_zadanegopytaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_rozwiazanegoquizu
        {
            get
            {
                return _ID_rozwiazanegoquizu;
            }
            set
            {
                OnID_rozwiazanegoquizuChanging(value);
                ReportPropertyChanging("ID_rozwiazanegoquizu");
                _ID_rozwiazanegoquizu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_rozwiazanegoquizu");
                OnID_rozwiazanegoquizuChanged();
            }
        }
        private global::System.Int32 _ID_rozwiazanegoquizu;
        partial void OnID_rozwiazanegoquizuChanging(global::System.Int32 value);
        partial void OnID_rozwiazanegoquizuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_pytania
        {
            get
            {
                return _ID_pytania;
            }
            set
            {
                OnID_pytaniaChanging(value);
                ReportPropertyChanging("ID_pytania");
                _ID_pytania = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_pytania");
                OnID_pytaniaChanged();
            }
        }
        private global::System.Int32 _ID_pytania;
        partial void OnID_pytaniaChanging(global::System.Int32 value);
        partial void OnID_pytaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_udzielonejodp
        {
            get
            {
                return _ID_udzielonejodp;
            }
            set
            {
                OnID_udzielonejodpChanging(value);
                ReportPropertyChanging("ID_udzielonejodp");
                _ID_udzielonejodp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_udzielonejodp");
                OnID_udzielonejodpChanged();
            }
        }
        private global::System.Int32 _ID_udzielonejodp;
        partial void OnID_udzielonejodpChanging(global::System.Int32 value);
        partial void OnID_udzielonejodpChanged();

        #endregion

    
    }

    #endregion

    
}
